"""
Alert — SQLAlchemy model for security and safety alerts
generated by the VoltGuard system.
"""

from datetime import datetime, timezone

from sqlalchemy import Column, Integer, String, Boolean, DateTime

from backend.database.database import Base


class Alert(Base):
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    severity = Column(String, nullable=False, default="INFO")   # INFO, WARNING, CRITICAL
    title = Column(String, nullable=False)
    message = Column(String, nullable=True)
    device = Column(String, nullable=True)
    acknowledged = Column(Boolean, default=False, nullable=False)

    def __repr__(self) -> str:
        return f"<Alert id={self.id} severity={self.severity} title={self.title!r}>"
