"""
Alert — SQLAlchemy model for security and safety alerts
generated by the VoltGuard system.

Phase 8 extensions:
  - status: ACTIVE / ACKNOWLEDGED / RESOLVED lifecycle
  - event_id: FK link to the originating SecurityEvent
  - acknowledged_at / resolved_at: lifecycle timestamps
  - severity extended to include CATASTROPHIC
"""

from datetime import datetime, timezone

from sqlalchemy import Column, Integer, String, Boolean, DateTime

from backend.database.database import Base


class Alert(Base):
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    severity = Column(String, nullable=False, default="INFO")   # INFO, WARNING, CRITICAL, CATASTROPHIC
    status = Column(String, nullable=False, default="ACTIVE")   # ACTIVE, ACKNOWLEDGED, RESOLVED
    title = Column(String, nullable=False)
    message = Column(String, nullable=True)
    device = Column(String, nullable=True)
    event_id = Column(Integer, nullable=True)                   # FK to SecurityEvent.id
    acknowledged = Column(Boolean, default=False, nullable=False)
    acknowledged_at = Column(DateTime, nullable=True)
    resolved_at = Column(DateTime, nullable=True)

    def __repr__(self) -> str:
        return f"<Alert id={self.id} severity={self.severity} status={self.status} title={self.title!r}>"
